### PR TITLE
[Python] Add example for gemini 1.5 

### PR DESCRIPTION
**Pull request by gabrielchua**
Added an example for Gemini 1.5, based on the [Google Generative AI SDK](https://ai.google.dev/gemini-api/docs/function-calling/tutorial?lang=python).

### CODE REVIEW

**Comment by mlejva** [comment]
Hi @gabrielchua, have you actually ran the code? There are several errors that prevent this from actually working

**Comment by gabrielchua** [comment]
Hi @mlejva yes - I did run the code - https://github.com/gabrielchua/e2b-cookbook/blob/main/examples/gemini-1.5-code-interpreter/gemini-1.5.ipynb

What are the errors you’re getting? 

i realised it may not be clear that this is using Google AI Studio, and not Vertex AI. The former’s for non-GCP users

**Comment by mlejva** [comment]
> Hi @mlejva yes - I did run the code - https://github.com/gabrielchua/e2b-cookbook/blob/main/examples/gemini-1.5-code-interpreter/gemini-1.5.ipynb
> 
> What are the errors you’re getting?
> 
> i realised it may not be clear that this is using Google AI Studio, and not Vertex AI. The former’s for non-GCP users

I'm getting an error with you're passing the `exec_python_code`:
```py
import google.generativeai as genai

# Configure the API key
genai.configure(api_key=GOOGLE_API_KEY)

# Initialize the model, and pass the system instruction and tools
model = genai.GenerativeModel(model_name=MODEL_NAME,
                              system_instruction=SYSTEM_PROMPT,
                              tools=[execute_python_code])
```

```
---------------------------------------------------------------------------
PydanticSchemaGenerationError             Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/google/generativeai/types/content_types.py in _make_tool(tool)
    700         try:
--> 701             return Tool(function_declarations=[tool])
    702         except Exception as e:

29 frames
PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'e2b_code_interpreter.main.CodeInterpreter'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.7/u/schema-for-unknown-type

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/google/generativeai/types/content_types.py in _make_tool(tool)
    701             return Tool(function_declarations=[tool])
    702         except Exception as e:
--> 703             raise TypeError(
    704                 "Expected an instance of `genai.ToolType`. Got a:\n" f"  {type(tool)=}",
    705                 tool,

TypeError: ("Expected an instance of `genai.ToolType`. Got a:\n  type(tool)=<class 'function'>", <function execute_python_code at 0x7cb02d303d90>)
```

**Comment by gabrielchua** [comment]
The errors could be an environment problem. 

Locally, I'm using Python `3.11` with the following packages, and it runs.

```
e2b==0.17.0
e2b-code-interpreter==0.0.6
google-generativeai==0.5.4
pydantic==2.7.1
```

I've tried the notebook in Co-Lab too (see [here](https://colab.research.google.com/drive/1k5886ZFjXfOf8A0RD9F7N_JyHiKQQ341#scrollTo=wPJ0WxpvavFo)). The co-lab runtime uses Python `3.10` with the following:

(same as above)
```
e2b==0.17.0
e2b-code-interpreter==0.0.6
google-generativeai==0.5.4
pydantic==2.7.1
```

**Comment by tizkovatereza** [comment]
> Locally, I'm using Python `3.11` with the following packages, and it runs.
> 
> ```
> e2b==0.17.0
> e2b-code-interpreter==0.0.6
> google-generativeai==0.5.4
> pydantic==2.7.1
> ```
> 
> I've tried the notebook in Co-Lab too (see [here](https://colab.research.google.com/drive/1k5886ZFjXfOf8A0RD9F7N_JyHiKQQ341#scrollTo=wPJ0WxpvavFo)). The co-lab runtime uses Python `3.10` with the following:
> 
> (same as above)
> 
> ```
> e2b==0.17.0
> e2b-code-interpreter==0.0.6
> google-generativeai==0.5.4
> pydantic==2.7.1
> ```


Hey @gabrielchua !
I tested it and getting this error (and it doesn't work either in the Google Collab).
I'm not sure what's the issue now, can you please check it? Otherwise the code looks good! 

Screenshot 2024-06-05 at 17 46 08
Screenshot 2024-06-05 at 17 46 36

**Pull request closed without merging**
